name: Build and Package ZMK Firmware
on: [push, pull_request]

jobs:
  # 第一步：手动编译固件（不再复用工作流）
  build-firmware:
    runs-on: ubuntu-latest
    steps:
      # 步骤1：拉取 ZMK 官方源码
      - name: Checkout ZMK
        uses: actions/checkout@v4
        with:
          repository: zmkfirmware/zmk
          path: zmk
          ref: main
          fetch-depth: 0

      # 步骤2：拉取你的配置文件（含 bt75_v1.conf 等）
      - name: Checkout User Config
        uses: actions/checkout@v4
        with:
          path: user-config
          fetch-depth: 1

      # 步骤3：初始化 ZMK 环境并编译
      - name: Build Firmware
        run: |
          cd zmk
          # 初始化 west 环境
          west init -l .
          west update
          # 编译：指定板型、配置目录、板型搜索路径（关键）
          west build -s app -b bt75_v1 \
                    -- -DZMK_CONFIG=../user-config/config \  # 你的配置目录
                       -DBOARD_ROOT=${PWD}/boards/arm/ckp  # 板型所在的 ckp 目录

      # 步骤4：上传编译产物（供后续打包用）
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: zmk/build/zephyr/*.uf2  # 固件路径（根据实际输出调整）

  # 第二步：打包步骤（无需修改，依赖上面的 build-firmware）
  package-firmware:
    needs: build-firmware
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: build
      
      - name: Check firmware files
        run: |
          echo "固件文件列表："
          ls -R build

      # 步骤3：压缩固件
      - name: Compress firmware
        run: |
          mkdir -p firmware_zip
          cp build/*.uf2 firmware_zip/  # 复制所有 .uf2 固件（根据实际类型调整）
          zip -r zmk_firmware.zip firmware_zip/

      # 步骤4：上传压缩包
      - name: Upload firmware zip
        uses: actions/upload-artifact@v4
        with:
          name: zmk-firmware-pack
          path: zmk_firmware.zip
          retention-days: 30
