name: ZMK Firmware Build
on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/**'
      - 'config/**'
  workflow_dispatch:
    inputs:
      keyboard:
        description: nice_nano_v2
        required: false
        default: 'all'

jobs:
  build-firmware:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      config-dir: config
      verbosity: debug
      keyboard: ${{ github.event.inputs.keyboard }}
    permissions:
      contents: read 
      actions: write 
