name: Build and Package ZMK Firmware

on: [push, pull_request]

jobs:
  # 第一步：复用官方工作流编译固件
  build-firmware:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      config_path: config/ # 你的配置文件路径

  # 第二步：在官方编译完成后，执行打包步骤（依赖第一步成功）
  package-firmware:
    needs: build-firmware  # 确保先完成编译
    runs-on: ubuntu-latest  # 必须指定运行环境
    steps:
      # 步骤1：下载官方编译产生的固件（build-output 是官方默认 artifacts 名称）
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: build  # 下载到本地 build 目录

      # 步骤2：检查固件是否存在（调试用）
      - name: Check firmware files
        run: |
          echo "固件文件列表："
          ls -R build

      # 步骤3：压缩固件
      - name: Compress firmware
        run: |
          mkdir -p firmware_zip
          cp build/*.uf2 firmware_zip/  # 复制所有 .uf2 固件（根据实际类型调整）
          zip -r zmk_firmware.zip firmware_zip/

      # 步骤4：上传压缩包
      - name: Upload firmware zip
        uses: actions/upload-artifact@v4
        with:
          name: zmk-firmware-pack
          path: zmk_firmware.zip
          retention-days: 30
