name: Build ZMK Firmware
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: custom-files
          fetch-depth: 1

      - name: Initialize ZMK Repo
        run: |
          git clone --depth 1 https://github.com/zmkfirmware/zmk.git ./zmk
          cd ./zmk
          west init -l .
          west update

      - name: Inject Custom Board and Config
        run: |
          # 注入板型文件
          mkdir -p ./zmk/app/boards/arm/ckp/bt75_v1
          cp -r custom-files/boards/arm/ckp/bt75_v1/* ./zmk/app/boards/arm/ckp/bt75_v1/
          # 注入配置和键位映射
          mkdir -p ./zmk/config
          cp -r custom-files/config/* ./zmk/config/

      - name: Build Firmware
        run: |
          cd ./zmk
          west build -s app -b bt75_v1 -- -DZMK_CONFIG=../config

      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: bt75_v1-firmware
          path: ./zmk/build/zephyr/*.uf2
