name: Build ZMK Firmware for bt75_v1
on: [push, pull_request]

jobs:
  build-firmware:
    runs-on: ubuntu-latest
    steps:
      # 步骤1：创建ZMK目录并通过官方仓库克隆获取west.yml（最可靠方式）
      - name: Clone ZMK Official Repo (to get valid west.yml)
        run: |
          # 直接克隆ZMK官方仓库的核心文件（含west.yml）
          git clone --depth 1 https://github.com/zmkfirmware/zmk.git ./zmk
          # 验证west.yml存在
          if [ ! -f "./zmk/west.yml" ]; then
            echo "Error: west.yml not found in ZMK repo"
            exit 1
          fi

      # 步骤2：拉取你的自定义配置（板型和配置文件）
      - name: Checkout Custom Files
        uses: actions/checkout@v4
        with:
          path: custom-files
          fetch-depth: 1

      # 步骤3：注入自定义板型到ZMK目录
      - name: Inject Custom Board (ckp/bt75_v1)
        run: |
          mkdir -p ./zmk/boards/arm
          cp -r custom-files/boards/arm/ckp ./zmk/boards/arm/
          # 验证板型文件
          if [ ! -d "./zmk/boards/arm/ckp/bt75_v1" ]; then
            echo "Error: bt75_v1 board files missing"
            exit 1
          fi

      # 步骤4：安装依赖
      - name: Install Dependencies
        run: |
          sudo apt update -y
          sudo apt install -y python3 python3-pip build-essential cmake ninja-build
          pip3 install west

      # 步骤5：初始化并编译
      - name: Build Firmware
        run: |
          cd ./zmk
          west init -l .
          west update
          west build -s app -b bt75_v1 \
                    -- -DZMK_CONFIG=../custom-files/config

      # 步骤6：上传固件
      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: bt75_v1-firmware
          path: ./zmk/build/zephyr/*.uf2
