name: Build ZMK Firmware (Repo: 2)
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取你的仓库（名称2）
        uses: actions/checkout@v4
        with:
          path: custom-files
          fetch-depth: 1

      - name: 检查 west.yml 是否存在
        run: |
          if [ ! -f "custom-files/west.yml" ]; then
            echo "❌ 错误：你的仓库根目录未找到 west.yml，请手动上传"
            exit 1
          fi
          echo "✅ 已找到 west.yml"

      - name: 准备本地编译目录
        run: |
          mkdir -p ./build-zmk
          cp custom-files/west.yml ./build-zmk/
          echo "✅ 编译目录准备完成"

      - name: 注入板型文件
        run: |
          mkdir -p ./build-zmk/boards/arm
          cp -r custom-files/boards/arm/ckp ./build-zmk/boards/arm/
          if [ ! -d "./build-zmk/boards/arm/ckp/bt75_v1" ]; then
            echo "❌ 错误：未找到 bt75_v1 板型文件"
            exit 1
          fi
          echo "✅ 板型文件注入成功"

      - name: 安装 west 工具
        run: |
          pip3 install --upgrade west
          if ! command -v west &> /dev/null; then
            echo "❌ 错误：west 工具安装失败"
            exit 1
          fi
          west --version
          echo "✅ west 工具可用"

      - name: 初始化 ZMK 环境
        run: |
          cd ./build-zmk
          west init -l .
          west update
          echo "✅ ZMK 环境初始化完成"

      - name: 编译 bt75_v1 固件
        run: |
          cd ./build-zmk
          west build -s app -b bt75_v1 -- -DZMK_CONFIG=../custom-files/config
          echo "✅ 固件编译完成"

      - name: 上传固件
        uses: actions/upload-artifact@v4
        with:
          name: bt75_v1-firmware
          path: ./build-zmk/build/zephyr/*.uf2
