name: ZMK Firmware Build
on:
  push:
    branches: [master]
    paths:
      - '.github/workflows/**'
      - 'config/**'
  workflow_dispatch:
    inputs:
      keyboard:
        description: '键盘型号（如 nice_nano_v2）'
        required: false
        default: 'all'
jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      config-dir: config
      verbosity: info
      keyboard: ${{ github.event.inputs.keyboard }}
    permissions:
      contents: read
      actions: write
