name: Build ZMK Firmware for Your Repo
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. 拉取你的仓库（含手动上传的west.yml）
      - name: 拉取仓库（含west.yml）
        uses: actions/checkout@v4
        with:
          path: custom-files
          fetch-depth: 1

      # 2. 移动west.yml到自定义目录（这里命名为"my-zmk"，可根据需求修改）
      - name: 移动west.yml到正确路径
        run: |
          mkdir -p ./2
          cp custom-files/west.yml ./2/
          if [ ! -f "./2/west.yml" ]; then
            echo "❌ 错误：west.yml未移动成功"
            exit 1
          fi
          echo "✅ west.yml已移动到2目录"

      # 3. 注入自定义板型
      - name: 注入板型文件
        run: |
          mkdir -p ./2/boards/arm
          cp -r custom-files/boards/arm/ckp ./2/boards/arm/
          if [ ! -d "./2/boards/arm/ckp/bt75_v1" ]; then
            echo "❌ 错误：未找到bt75_v1板型文件"
            exit 1
          fi
          echo "✅ 板型文件注入成功"

      # 4. 安装并验证west
      - name: 安装west工具
        run: |
          pip3 install --upgrade west
          if ! command -v west &> /dev/null; then
            echo "❌ 错误：west未安装成功"
            exit 1
          fi
          west --version
          echo "✅ west安装验证成功"

      # 5. 初始化ZMK环境
      - name: 初始化环境
        run: |
          cd ./2
          west init -l .
          west update
          echo "✅ 环境初始化完成"

      # 6. 编译固件
      - name: 编译固件
        run: |
          cd ./2
          west build -s app -b bt75_v1 \
                    -- -DZMK_CONFIG=../custom-files/config
          echo "✅ 固件编译完成"

      # 7. 上传固件
      - name: 上传固件
        uses: actions/upload-artifact@v4
        with:
          name: bt75_v1-firmware
          path: ./2/build/zephyr/*.uf2
