name: Build ZMK Firmware with Custom Board
on: [push, pull_request]

jobs:
  build-firmware:
    runs-on: ubuntu-latest
    steps:
      # 步骤1：创建并进入 zmk 目录，下载官方 west.yml
      - name: 初始化 ZMK 目录并下载 west.yml
        run: |
          mkdir -p zmk
          cd zmk
          curl -O https://raw.githubusercontent.com/zmkfirmware/zmk/main/west.yml
          ls -la  # 验证 west.yml 存在

      # 步骤2：拉取你的自定义板型和配置
      - name: 拉取自定义文件
        uses: actions/checkout@v4
        with:
          path: custom-files
          fetch-depth: 1

      # 步骤3：注入自定义板型到 zmk 目录
      - name: 注入自定义板型 (ckp)
        run: |
          mkdir -p zmk/boards/arm
          cp -r custom-files/boards/arm/ckp zmk/boards/arm/
          ls -la zmk/boards/arm/ckp/bt75_v1  # 验证板型文件

      # 步骤4：安装依赖（含 west 工具）
      - name: 安装依赖
        run: |
          sudo apt update -y
          sudo apt install -y python3 python3-pip build-essential cmake ninja-build
          pip3 install west
          west --version

      # 步骤5：编译固件
      - name: 构建固件
        run: |
          cd zmk
          west init -l .  # 基于当前目录的 west.yml 初始化
          west update
          west build -s app -b bt75_v1 \
                    -- -DZMK_CONFIG=../custom-files/config

      # 步骤6：上传固件
      - name: 上传固件
        uses: actions/upload-artifact@v4
        with:
          name: bt75_v1-firmware
          path: zmk/build/zephyr/*.uf2
