name: Build ZMK Firmware

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
        
    - name: Build
      uses: zmkfirmware/zmk-build-action@v0.3.0
      with:
        board: nice_nano_v2
        shield: your_shield_name
        
    - name: Upload Firmware
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: firmware-*.zip
        retention-days: 30
